document.addEventListener("DOMContentLoaded", () => {
    init();
});

function init() {
    const hasTemplate = document.getElementById("hasTemplate");
    const fileInput = document.getElementById("templateFile");
    const dropArea = document.getElementById("dropArea");

    hasTemplate.addEventListener("change", toggleTemplateMode);

    document.getElementById("exportPdfBtn")
        .addEventListener("click", exportPDF);

    // Drag & drop support
    if (dropArea) {
        dropArea.addEventListener("click", () => fileInput.click());

        dropArea.addEventListener("dragover", (e) => {
            e.preventDefault();
            dropArea.style.border = "2px dashed #1f4ea3";
        });

        dropArea.addEventListener("dragleave", () => {
            dropArea.style.border = "none";
        });

        dropArea.addEventListener("drop", (e) => {
            e.preventDefault();
            const file = e.dataTransfer.files[0];
            handleFile(file);
        });
    }

    fileInput.addEventListener("change", (e) => {
        handleFile(e.target.files[0]);
    });

    toggleTemplateMode();
}

/* -----------------------------
   TEMPLATE MODE (YES / NO)
------------------------------*/
function toggleTemplateMode() {
    const mode = document.getElementById("hasTemplate").value;

    const yesSection = document.getElementById("yesTemplateSection");
    const noSection = document.getElementById("noTemplateSection");

    if (mode === "yes") {
        yesSection.classList.remove("hidden");
        noSection.classList.add("hidden");
    } else {
        yesSection.classList.add("hidden");
        noSection.classList.remove("hidden");
    }
}

/* -----------------------------
   FILE VALIDATION
------------------------------*/
function handleFile(file) {
    if (!file) return;

    const allowedTypes = [
        "application/pdf",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ];

    if (!allowedTypes.includes(file.type)) {
        alert("Only PDF or DOCX files are allowed!");
        return;
    }

    alert(`File uploaded: ${file.name}`);
}

/* -----------------------------
   COLLECT FORM DATA
------------------------------*/
function collectData() {
    return {
        company: document.getElementById("company")?.value || "",
        role: document.getElementById("role")?.value || "",
        reportType: document.getElementById("reportType")?.value || "",
        tool: document.getElementById("tool")?.value || "",
        pain: document.getElementById("pain")?.value || "",
        hasTemplate: document.getElementById("hasTemplate")?.value || ""
    };
}

/* -----------------------------
   EXPORT PDF (REAL STRUCTURE)
------------------------------*/
function exportPDF() {
    const data = collectData();

    const content = `
EviNDT - Template Collection Report

====================================

USER INFORMATION
----------------
Company: ${data.company}
Role: ${data.role}
Report Type: ${data.reportType}
Current Tool: ${data.tool}
Main Pain: ${data.pain}

====================================

TEMPLATE STATUS
---------------
Has Template: ${data.hasTemplate}

====================================
Generated by EviNDT System
    `;

    generatePDF(content);
}

/* -----------------------------
   PDF GENERATOR
   (uses browser print → PDF)
------------------------------*/
function generatePDF(textContent) {
    const win = window.open("", "_blank");

    win.document.write(`
        <html>
        <head>
            <title>EviNDT Report</title>
            <style>
                body {
                    font-family: Arial;
                    padding: 30px;
                    line-height: 1.6;
                    white-space: pre-line;
                }
                h1 {
                    color: #1f4ea3;
                }
            </style>
        </head>
        <body>
            <h1>EviNDT Template Report</h1>
            <div>${textContent}</div>
        </body>
        </html>
    `);

    win.document.close();
    win.print();
}
